name: cicd

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  Deploy_To_Dev:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Source
        uses: actions/checkout@v2.3.4
      - name: Checkout Configs
        uses: actions/checkout@v2.3.4
        with:
          ref: dev-configs
          path: configs        
      - name: Generate Manifests
        run: |
          .github/workflows/utils/generate-manifests.sh ${{ github.workspace }}/services ${{ github.workspace }}/configs manifests
      - name: Create PR
        run: |        
          .github/workflows/utils//create-pr.sh -s ${{ github.workspace }}/manifests -d . -r ${{ secrets.MANIFESTS_REPO }} -b dev -i ${{ github.run_number }} -t ${{ secrets.MANIFESTS_TOKEN }} -m Y
  



